dubbo:
  application:
    name: server-consumer
  registry:
    address: nacos://127.0.0.1:8848
  #    address: zookeeper://192.168.126.22:2181
  consumer:
    check: false
server:
  port: 8080

spring:
  thymeleaf:
    cache: false