spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///studb
    username: root
    password: admin
dubbo:
  application:
    name: server-provider
  registry:
    address: zookeeper://192.168.202.128:2181
server:
  port: 8081
