spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql:///myclassdb
dubbo:
  application:
    name: myclass-service
  registry:
    address: zookeeper://192.168.126.22:2181
  protocol:
    port: 20881
server:
  port: 8082
